BUG:  Install missing library libatomic
```txt
411.0 /tmp/tmp.9qZYWcxd6F/rustup-init: error while loading shared libraries: libatomic.so.1: cannot open shared object file: No such file or directory
411.0 /tmp/tmp.9qZYWcxd6F/rustup-init: error while loading shared libraries: libatomic.so.1: cannot open shared object file: No such file or directory
------
Dockerfile:97
--------------------
  96 |
  97 | >>> RUN \
  98 | >>>   X86_FLAG=$([ "$DEFAULT_DOCKCROSS_IMAGE" = "dockcross/manylinux2014-x86" ] && echo "-32" || echo "") && \
  99 | >>>   /buildscripts/build-and-install-openssl.sh $X86_FLAG && \
 100 | >>>   /buildscripts/build-and-install-openssh.sh && \
 101 | >>>   /buildscripts/build-and-install-curl.sh && \
 102 | >>>   /buildscripts/build-and-install-git.sh && \
 103 | >>>   /buildscripts/build-and-install-cmake.sh $X86_FLAG && \
 104 | >>>   /buildscripts/build-and-install-rustup.sh && \
 105 | >>>   /buildscripts/install-liquidprompt-binary.sh && \
 106 | >>>   PYTHON=$([ -e /opt/python/cp38-cp38/bin/python ] && echo "/opt/python/cp38-cp38/bin/python" || echo "python3") && \
 107 | >>>   /buildscripts/install-python-packages.sh -python ${PYTHON} && \
 108 | >>>   /buildscripts/build-and-install-ninja.sh -python ${PYTHON} && \
 109 | >>>   /buildscripts/build-and-install-flatcc.sh && \
 110 | >>>   rm -rf /buildscripts
 111 |
--------------------
ERROR: failed to solve: process "/bin/sh -c X86_FLAG=$([ \"$DEFAULT_DOCKCROSS_IMAGE\" = \"dockcross/manylinux2014-x86\" ] && echo \"-32\" || echo \"\") &&   /buildscripts/build-and-install-openssl.sh $X86_FLAG &&   /buildscripts/build-and-install-openssh.sh &&   /buildscripts/build-and-install-curl.sh &&   /buildscripts/build-and-install-git.sh &&   /buildscripts/build-and-install-cmake.sh $X86_FLAG &&   /buildscripts/build-and-install-rustup.sh &&   /buildscripts/install-liquidprompt-binary.sh &&   PYTHON=$([ -e /opt/python/cp38-cp38/bin/python ] && echo \"/opt/python/cp38-cp38/bin/python\" || echo \"python3\") &&   /buildscripts/install-python-packages.sh -python ${PYTHON} &&   /buildscripts/build-and-install-ninja.sh -python ${PYTHON} &&   /buildscripts/build-and-install-flatcc.sh &&   rm -rf /buildscripts" did not complete successfully: exit code: 1
```